site_name: Embedding-Kit
nav:
  - Home: index.md
  - About: about.md
  - Examples: examples.md
  - API: api.md
theme: readthedocs

plugins:
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            show_source: false # Example option